# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a06ef1bf9c208901297fbfc902561e7eaa148ba930fd9d471c8fb1ce45905c0fd75bf72b49df77c4e3d393864ec9e45ede6fb0e9a3874a798f3d714fcbb0bb8

test:
  secret_key_base: e073b5a6643d265531566a3d4c560c29f8bd1d53f9fcb890375abae1406ed2c45d58d057131786de5a9e5bbeceb04e5465cb69b422f63535d14bfcfe3177cc17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
